fun main() {
    println("Listas - Venta de Motos")
    println("Inmutables")
    val modelos = listOf("MT-07", "CB190R", "V-Strom", "Ninja 400", "Bajaj Pulsar")
    println(modelos)
    println("Size: ${modelos.size}")
    println("Mostrar el elemento indice 0: ${modelos[0]}")
    println("Mostrar primer elemento: ${modelos.first()}")
    println("Mostrar ultimo elemento: ${modelos.last()}")
    println("Mostrar el elemento indice 2: ${modelos.get(2)}")
    println("Indice de MT-07: ${modelos.indexOf("MT-07")}")
    println("Existe CB190R? ${modelos.contains("CB190R")}")
    println("Existe Harley? ${"Harley" in modelos}")

    println("Sublista: ${modelos.subList(1, 4)}")
    println("Tomar primeros 2: ${modelos.take(2)}")
    println("Suprimir 3 primeros: ${modelos.drop(3)}")
    println("Tomar ultimos 2: ${modelos.takeLast(2)}")
    println(modelos)

    println("Mutables")
    val coloresMoto = mutableListOf("Negro", "Azul", "Rojo", "Blanco")
    println(coloresMoto)
    coloresMoto.add("Verde")
    println(coloresMoto)
    coloresMoto.add(1, "Gris")
    println(coloresMoto)
    coloresMoto.remove("Verde")
    println(coloresMoto)
    coloresMoto[1] = "Plateado"
    println(coloresMoto)

    println("Array deque")
    val precios = ArrayDeque<Double>()
    println(precios)
    precios.addFirst(7500.0)
    println(precios)
    precios.addFirst(8200.0)
    println(precios)
    precios.addLast(6500.0)
    println(precios)
    precios.removeFirst()
    println(precios)
    precios.removeLast()
    println(precios)
}
