fun main() {
    println("Set - Venta de Motos")
    println("Inmutables")
    val codigosMoto = setOf(101, 202, 303, 404, 505, 303, 202, 101, 101)
    println(codigosMoto)

    println("Operaciones de Conjuntos")
    val motosGasolina = setOf(101, 202, 303, 404, 505)
    println("Gasolina $motosGasolina")
    val motosElectricas = setOf(202, 404, 606, 808)
    val motosImportadas = setOf(303, 606, 909, 101)
    println("Electricas $motosElectricas")
    println("union ${motosGasolina union motosElectricas}")
    println("interseccion ${motosGasolina intersect motosElectricas}")
    println("interseccion ${motosImportadas intersect motosElectricas}")
    println("substraccion ${motosGasolina subtract motosElectricas}")
    println("substraccion ${motosGasolina subtract motosImportadas}")

    println("Set Mutables")
    val marcas = mutableSetOf("Yamaha", "Honda", "Suzuki", "Kawasaki")
    println(marcas)
    marcas.add("Yamaha")
    println(marcas)
    marcas.add("BMW")
    println(marcas)
    marcas.remove("Suzuki")
    println(marcas)
    println("Existe Yamaha? ${"Yamaha" in marcas}")
    println("Existe Ducati? ${"Ducati" in marcas}")
}
